### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by Paillat-dev** [laToufff/blind-test#1]
I am really sad. I was looking for an automated blind test game, and found this. All of a sudden, I tought I had found the exact project I needed to play with my friends late at night. but there is no documentation and now I don't know how to use it.

Now I am very sad because of you.

**Comment by laToufff** [comment]
Cry about it

**Comment by laToufff** [comment]
I will add documentation as soon as I get the thing to work well enough to call it usable
